// next/remote/app/page.tsx
'use client';

import { useEffect, useState } from 'react';
import type { DeploymentContext, MonitorEvent } from '@pilot/contracts';
import { DEFAULT_CONTEXT } from '@pilot/fixtures';
import { Monitor } from '../components/monitor';
import { parseHostContextMessage, postMessageToHost } from '../lib/frame-adapter';
import { resolveContextFromQuery } from '../lib/context';

const HOST_ORIGIN = 'http://127.0.0.1:3000';

export default function RemoteHealthPage() {
  const [context, setContext] = useState<DeploymentContext>(DEFAULT_CONTEXT);
  const [isFramed, setIsFramed] = useState(false);

  useEffect(() => {
    const framed = window.parent !== window;
    setIsFramed(framed);
    setContext(resolveContextFromQuery(window.location.search, DEFAULT_CONTEXT));

    if (!framed) return;

    postMessageToHost(window.parent, HOST_ORIGIN, { type: 'monitor-ready' });

    function handleHostMessage(event: MessageEvent): void {
      const payload = parseHostContextMessage(event, HOST_ORIGIN);
      if (payload) setContext(payload);
    }

    window.addEventListener('message', handleHostMessage);
    return () => window.removeEventListener('message', handleHostMessage);
  }, []);

  function forwardToHost(event: MonitorEvent): void {
    if (isFramed) postMessageToHost(window.parent, HOST_ORIGIN, event);
  }

  return (
    <main className="mx-auto max-w-3xl p-8">
      <header className="mb-6">
        <p className="m-0 mb-2 font-mono text-xs uppercase tracking-wide text-[hsl(var(--platform-accent))]">
          Model Deployment Monitor
        </p>
        <h1 className="m-0 font-[family-name:var(--font-display)] text-4xl tracking-tight">Next Remote</h1>
      </header>
      <Monitor
        context={context}
        onDeploymentSelected={(id) => forwardToHost({ type: 'deployment-selected', deploymentId: id })}
        onAlertAcknowledged={(id) => forwardToHost({ type: 'alert-acknowledged', deploymentId: id })}
      />
    </main>
  );
}

// vue/remote/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, reactive } from 'vue';
import type { DeploymentContext, MonitorEvent } from '@pilot/contracts';
import { DEFAULT_CONTEXT } from '@pilot/fixtures';
import Monitor from './components/Monitor.vue';
import { resolveContextFromQuery } from './lib/context';
import { parseHostContextMessage, postMessageToHost } from './lib/frameAdapter';

/** Vue Host serves on this fixed port; only its exact origin is trusted for postMessage. */
const HOST_ORIGIN = `${window.location.protocol}//${window.location.hostname}:4173`;

const isFramed = window.parent !== window;

const context = reactive<DeploymentContext>(
  resolveContextFromQuery(window.location.search, DEFAULT_CONTEXT),
);

function handleHostMessage(event: MessageEvent): void {
  const payload = parseHostContextMessage(event, HOST_ORIGIN);
  if (payload) {
    Object.assign(context, payload);
  }
}

function forwardToHost(event: MonitorEvent): void {
  if (isFramed) {
    postMessageToHost(window.parent, HOST_ORIGIN, event);
  }
}

onMounted(() => {
  if (isFramed) {
    window.addEventListener('message', handleHostMessage);
    postMessageToHost(window.parent, HOST_ORIGIN, { type: 'monitor-ready' });
  }
});

onUnmounted(() => {
  if (isFramed) {
    window.removeEventListener('message', handleHostMessage);
  }
});
</script>

<template>
  <main class="remote-shell">
    <header class="remote-shell__header">
      <p class="remote-shell__eyebrow">Model Deployment Monitor</p>
      <h1 class="remote-shell__title">Vue Remote</h1>
    </header>
    <Monitor
      :context="context"
      @deployment-selected="(id) => forwardToHost({ type: 'deployment-selected', deploymentId: id })"
      @alert-acknowledged="(id) => forwardToHost({ type: 'alert-acknowledged', deploymentId: id })"
    />
  </main>
</template>

<style scoped>
.remote-shell {
  padding: 2rem;
  max-width: 48rem;
  margin: 0 auto;
}

.remote-shell__header {
  margin-bottom: 1.5rem;
}

.remote-shell__eyebrow {
  font-family: var(--font-mono);
  color: hsl(var(--platform-accent));
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-size: 0.75rem;
  margin: 0 0 0.5rem;
}

.remote-shell__title {
  font-family: var(--font-display);
  margin: 0;
}
</style>
