// vue/standalone/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { DeploymentContext, MonitorEvent } from '@pilot/contracts';
import { DEFAULT_CONTEXT } from '@pilot/fixtures';
import { Badge } from './components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from './components/ui/card';
import ContextControls from './components/ContextControls.vue';
import EventLedgerPanel from './components/EventLedgerPanel.vue';
import Monitor from './components/Monitor.vue';
import { createEventLedger } from './lib/eventLedger';

const context = ref<DeploymentContext>({ ...DEFAULT_CONTEXT });
const ledger = createEventLedger();

function updateContext(next: DeploymentContext): void {
  context.value = next;
}

function recordEvent(event: MonitorEvent): void {
  ledger.record(event);
}
</script>

<template>
  <main class="console-shell">
    <header class="console-header">
      <div>
        <p class="console-eyebrow">AI Platform Console + Model Deployment Monitor</p>
        <h1>Flight Deck Ledger</h1>
        <p class="console-summary">
          Non-composed baseline: deployment context and monitor evidence in one Vue application, no
          Module Federation and no iframe.
        </p>
      </div>
      <Badge variant="secondary">Vue Standalone · 4175</Badge>
    </header>

    <Card class="control-deck">
      <CardHeader>
        <CardTitle>Deployment context</CardTitle>
      </CardHeader>
      <CardContent class="control-deck__content">
        <ContextControls :context="context" @update:context="updateContext" />
      </CardContent>
    </Card>

    <section class="composition-grid" aria-label="Deployment monitor and event ledger">
      <div class="composition-stage">
        <Monitor
          :context="context"
          @deployment-selected="(id) => recordEvent({ type: 'deployment-selected', deploymentId: id })"
          @alert-acknowledged="(id) => recordEvent({ type: 'alert-acknowledged', deploymentId: id })"
        />
      </div>
      <EventLedgerPanel :entries="ledger.entries.value" />
    </section>
  </main>
</template>

<style scoped>
.console-shell {
  width: min(94rem, 100%);
  margin: 0 auto;
  padding: clamp(1rem, 2.5vw, 2.5rem);
}

.console-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 1rem;
  margin-bottom: 1.25rem;
}

.console-eyebrow {
  margin: 0 0 0.35rem;
  color: hsl(var(--platform-accent));
  font-family: var(--font-mono);
  font-size: 0.72rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

h1 {
  margin: 0;
  font-family: var(--font-display);
  font-size: clamp(2rem, 4vw, 3.7rem);
  letter-spacing: -0.045em;
}

.console-summary {
  max-width: 44rem;
  margin: 0.55rem 0 0;
  color: hsl(var(--platform-muted));
}

.control-deck,
.composition-stage {
  border-color: hsl(var(--platform-border));
  background: hsl(var(--platform-surface));
}

.control-deck__content {
  display: grid;
  gap: 1rem;
}

.composition-grid {
  display: grid;
  grid-template-columns: minmax(0, 2fr) minmax(18rem, 0.8fr);
  gap: 1rem;
  margin-top: 1rem;
}

.composition-stage {
  min-height: 28rem;
  padding: clamp(0.75rem, 2vw, 1.25rem);
  border: 1px solid hsl(var(--platform-border));
  border-radius: var(--radius);
}

@media (max-width: 900px) {
  .composition-grid {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 560px) {
  .console-header {
    flex-direction: column;
  }
}
</style>

// next/standalone/app/page.tsx
'use client';

import { useState } from 'react';
import type { DeploymentContext } from '@pilot/contracts';
import { DEFAULT_CONTEXT } from '@pilot/fixtures';
import { Badge } from '../components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { ContextControls } from '../components/context-controls';
import { EventLedgerPanel } from '../components/event-ledger-panel';
import { Monitor } from '../components/monitor';
import { useEventLedger } from '../lib/event-ledger';

export default function StandalonePage() {
  const [context, setContext] = useState<DeploymentContext>({ ...DEFAULT_CONTEXT });
  const ledger = useEventLedger();

  return (
    <main className="mx-auto w-[min(94rem,100%)] p-[clamp(1rem,2.5vw,2.5rem)]">
      <header className="mb-5 flex items-start justify-between gap-4">
        <div>
          <p className="m-0 mb-1.5 font-mono text-xs uppercase tracking-wide text-[hsl(var(--platform-accent))]">
            AI Platform Console + Model Deployment Monitor
          </p>
          <h1 className="m-0 font-[family-name:var(--font-display)] text-[clamp(2rem,4vw,3.7rem)] tracking-tight">
            Flight Deck Ledger
          </h1>
          <p className="mt-2 max-w-2xl text-[hsl(var(--platform-muted))]">
            Non-composed baseline: deployment context and monitor evidence in one Next application, no
            Module Federation and no iframe.
          </p>
        </div>
        <Badge variant="secondary">Next Standalone · 3002</Badge>
      </header>

      <Card className="mb-4 border-[hsl(var(--platform-border))] bg-[hsl(var(--platform-surface))]">
        <CardHeader>
          <CardTitle>Deployment context</CardTitle>
        </CardHeader>
        <CardContent>
          <ContextControls context={context} onContextChange={setContext} />
        </CardContent>
      </Card>

      <section
        aria-label="Deployment monitor and event ledger"
        className="grid grid-cols-1 gap-4 min-[900px]:grid-cols-[minmax(0,2fr)_minmax(18rem,0.8fr)]"
      >
        <div className="min-h-[28rem] rounded-[var(--radius)] border border-[hsl(var(--platform-border))] bg-[hsl(var(--platform-surface))] p-[clamp(0.75rem,2vw,1.25rem)]">
          <Monitor
            context={context}
            onDeploymentSelected={(id) => ledger.record({ type: 'deployment-selected', deploymentId: id })}
            onAlertAcknowledged={(id) => ledger.record({ type: 'alert-acknowledged', deploymentId: id })}
          />
        </div>
        <EventLedgerPanel entries={ledger.entries} />
      </section>
    </main>
  );
}
